In [1]:
import numpy as np

In [2]:
x=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [3]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
#check the diamension 
x.ndim


2

In [5]:
#check data type
x.dtype


dtype('int32')

In [6]:
#with the help shape it will give no of row and column
x.shape

(3, 4)

In [7]:
#indexing on numpy


In [8]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
x[0]

array([1, 2, 3, 4])

In [10]:
x[1]

array([5, 6, 7, 8])

In [11]:
x[2]

array([ 9, 10, 11, 12])

In [ ]:
#by using indexing by default it will give row

In [13]:
#suppose  i want to fetch 3rd element of first row
x[0,2]

3

In [14]:
# i want to change type of dtype
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
# i want to change type of dtype
a=np.array([1,2,3,4])

In [20]:
a.ndim

1

In [21]:
a.dtype

dtype('int32')

In [22]:
np.array([1,2,3,4],dtype='int64')

array([1, 2, 3, 4], dtype=int64)

In [23]:
np.array([1,2,3,4],dtype='bool')

array([ True,  True,  True,  True])

In [24]:
np.array([1,2,3,4],dtype='float')

array([1., 2., 3., 4.])

In [25]:
# suppose i want to number 1 to 20
#we can use arange function

In [31]:
np.arange(1,20)

array([ 1,  4,  7, 10, 13, 16, 19])

In [32]:
# here we can use step 

In [33]:
np.arange(1,30,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [34]:
# soppose i want to all zeros

In [36]:
j=np.zeros(5)

In [37]:
j.dtype

dtype('float64')

In [38]:
# by default datatype is flot we change explicitly

In [39]:
j=np.zeros(5,dtype='int64')

In [40]:
j

array([0, 0, 0, 0, 0], dtype=int64)

In [41]:
#suppose i want all value with 1
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [42]:
#here also by defult datatype is float
np.ones(10,dtype='int64')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [44]:
#suppose i want identity matrix of 5 rows and 5 columns
np.eye(5,5,dtype='int64')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int64)

In [48]:
# by using alternate method
np.identity(5,dtype='int64')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int64)

In [49]:
#suppose my array is 2d i want to convert it into 1d
j=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,10],[11,12,13,14]])

In [50]:
j

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 10],
       [11, 12, 13, 14]])

In [51]:
j.ravel() # it convert 1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 10, 11, 12, 13, 14])

In [52]:
j.ndim

2

In [53]:
j

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 10],
       [11, 12, 13, 14]])

In [57]:
j.flatten() # it return copy of 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 10, 11, 12, 13, 14])

In [58]:
j

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 10],
       [11, 12, 13, 14]])

In [59]:
j

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 10],
       [11, 12, 13, 14]])

In [60]:
#suppose i want to convert in to list
j.tolist()

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 10], [11, 12, 13, 14]]